### ISSUE TITLE
Case sensitive documentation issue on Docker Hub page

### ISSUE THREAD

**Issue by cyounkins** [sjmayotte/route53-dynamic-dns#14]
The Docker Hub page contains text like "LOG_TO_STDOUT=True is recommended...", using `True` and `False` instead of `true` and `false`. The uppercase examples will not work and causes an exception with the JSON parser.

**Comment by sjmayotte** [comment]
Documentation on Dockerhub has been updated to be consistent with Github.  Thanks for letting me know about the issue.
