### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ishalem** [sjmayotte/route53-dynamic-dns#15]
Is it possible to add the ability to set more than 1 domain (same IP)

I have several A records I need to update when my public IP changes

**Comment by PopTudor** [comment]
@ishalem It seems the AWS SDK doesn't support that by default so the library must make multiple requests or batch them together somehow... I created a compose file with a single .env file to define variables and duplicated the setting for each of my subdomains... works fine at the cost of using more resources

**Comment by sjmayotte** [comment]
Agree with @PopTudor solution.  The containers are very lite and you should be able to run one for each A record without any issues.

@ishalem let me know if you have any other questions.
