### ISSUE TITLE
Last-Known-IP.log conflict with running as alternate user

### ISSUE THREAD

**Issue by 101100** [sjmayotte/route53-dynamic-dns#23]
I'm using the project in a docker container and it is working well except for one issue.  I'd like to run the container as a different user as the default is user 1000 which is a real user account on my server. I also don't want to run the container as root. Because of this, the application does not have access to `Last-Known-IP.log` and even if I mount that file via docker, that also causes an issue because it cannot be removed on startup.

To fix this, it would be nice if `Last-Known-IP.log` was saved to `/tmp` (or to a `log` subdirectory) or the command `chmod 777 /usr/src/app` was added during build so that any user can save the log file. If either of these are acceptable, I'll happily make a PR to make the change.

Thanks for the project!

**Comment by sjmayotte** [comment]
@101100 Using 777 isn't ideal.  It would be better to use a different solution where user has proper permission. Go ahead and submit a PR with the change and I'll get it merged and deployed along with other open PR.

**Comment by 101100** [comment]
Would you prefer putting that in `/tmp` or in `log` in the current directory?

**Comment by sjmayotte** [comment]
Either is fine, just make sure you update the docs as part of PR
