### ISSUE TITLE
Updating AAAA record fails, grabs IPv4 address instead of IPv6

### ISSUE THREAD

**Issue by ohshitgorillas** [sjmayotte/route53-dynamic-dns#45]
Hello, I am trying to use this container to update an AAAA record but am receiving the following errors:

```
} InvalidChangeBatch: [Invalid Resource Record: 'FATAL problem: AAAARRDATAIllegalIPv6Address (Value is not a valid IPv6 address) encountered with '73.151.xxx.xx'']
    at de_InvalidChangeBatchRes (/usr/src/app/node_modules/@aws-sdk/client-route-53/dist-cjs/protocols/Aws_restXml.js:5168:23)
    at de_ChangeResourceRecordSetsCommandError (/usr/src/app/node_modules/@aws-sdk/client-route-53/dist-cjs/protocols/Aws_restXml.js:1922:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /usr/src/app/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /usr/src/app/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /usr/src/app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

Clearly, the container is trying to pull the IPv4 address rather than IPv6. I'm not sure how this container grabs the IPv4 address, but in the case that ROUTE53_TYPE=AAAA, it should grab the IPv6 address instead. 

Perhaps there's an alternative IP checker that will return IPv6 that I'm not aware of?

aws6.env:
```
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=us-west-1
ROUTE53_HOSTED_ZONE_ID=
ROUTE53_DOMAIN=my.server.addr
ROUTE53_TYPE=AAAA
ROUTE53_TTL=60
UPDATE_FREQUENCY=60000
TZ=America/Los_Angeles
LOG_TO_STDOUT=true
IPCHECKER=ifconfig.co
```

docker-compose:
```
services:
  wg_ddns6:
    image: sjmayotte/route53-dynamic-dns:latest
    container_name: wg_ddns6
    env_file:
      - ./aws6.env
```

Running the container in network_mode: host appears to resolve this problem... but is there another way besides host networking?

**Comment by ismarslomic** [comment]
This container supports 2 different IP checker sites:
- [ipify.org](https://api.ipify.org)
- [ifconfig.co](https://ifconfig.co/ip)

In your case you are using the [ifconfig.co](https://ifconfig.co/ip) and I assume that this site by default responds with IPv4. I see from their site that you can pass arguments whether you want to force it to return IPv4 or IPv6 when using the command line. But currently the code in [this container uses the HTTP](https://github.com/sjmayotte/route53-dynamic-dns/blob/master/server.js#L212).

So the short answer is that IPv6 is not supported currently. You are welcome to submit a PR with this feature.

**Comment by ohshitgorillas** [comment]
Actually, the default value returned by ifconfig.co is IPv6 when available.

Discussing this with a friend, he pointed out that to get the container out of host mode, the container would need an IPv6 address from docker to make sure the request goes out over IPv6, and that's what the IP checker would grab--not the host's IPv6, but the container's. Since grabbing the host's IPv6 is the desired behavior, network_mode: host is the appropriate solution.

**Comment by ismarslomic** [comment]
Good to know! Thanks for sharing the solution @ohshitgorillas!
