### ISSUE TITLE
disable email

### ISSUE THREAD

**Issue by lgrapenthin** [sjmayotte/route53-dynamic-dns#8]
It appears to be impossible to prevent the sending of emails from happening, even though the documentation hints that SEND_EMAIL_SES would do that.

The only workaround I know was to give the IAM user no permission to send emails.

**Comment by tombastianello** [comment]
I've written a fix for this with PR #9 - Waiting on a response to see if we can merge this

**Comment by sjmayotte** [comment]
This was merged and should be working now on latest version.  New release coming shortly that will include as well.
